In [64]:
import pandas as pd
import numpy as np

In [65]:
data_path = "C:\\Users\\User\\Documents\\4. Fourth Year\\Project\\Railway-Fares\Data\\Cleansed Data\\"

In [66]:
datazone_map = pd.read_csv(data_path + "station_datazone.csv", dtype = str)
station = pd.read_csv(data_path + "station.csv", dtype = str)
dz_lookup = pd.read_csv(r"C:\Users\User\Documents\4. Fourth Year\Project\Railway-Fares\Data\SIMD Postcode Lookup.csv")

In [67]:
failed = datazone_map[datazone_map["Data_Zone"].isna()]

In [75]:
failed = failed.merge(station, on = "NLC")

In [69]:
dz_lookup[dz_lookup["Postcode"].str.startswith("EH1 1BB")]

,Postcode,DZ,SIMD2020v2_Rank,SIMD2020v2_Vigintile,SIMD2020v2_Decile,SIMD2020v2_Quintile
32832,EH1 1BB,S01008676,3285,10,5,3

In [70]:
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup 
import re

In [71]:
urls = [f"https://en.wikipedia.org/wiki/UK_railway_stations_%E2%80%93_{letter}" for letter in "ABCDEFGHIJKLMNOPQRSTUVWXYZ"]
station_info = []

In [72]:
for url in urls:
    print(f"Getting {url[-1]}")
    page = requests.get(url)
    soup = BeautifulSoup(page.content, 'html.parser')
    rows = soup.find_all("tr")
    for row in rows:
        cols = row.find_all("a")
        try:
            station_info.append([cols[1].text, cols[2].text[:3]])
        except Exception:
            continue

Getting A
Getting B
Getting C
Getting D
Getting E
Getting F
Getting G
Getting H
Getting I
Getting J
Getting K
Getting L
Getting M
Getting N
Getting O
Getting P
Getting Q
Getting R
Getting S
Getting T
Getting U
Getting V
Getting W
Getting X
Getting Y
Getting Z

In [76]:
df = pd.DataFrame(station_info)

In [77]:
scottish = df.merge(failed, left_on = 1, right_on = "CRS")

In [78]:
scottish

,0,1,NLC,Data_Zone,Intermediate_Zone,Council_area,Postcode,CRS,lat,lon,Name
0,AB11 6RT,ABD,8976,NaN,NaN,NaN,AB11 6RT,ABD,57.144143,-2.098785,Aberdeen
1,FK10 1BA,ALO,9883,NaN,NaN,NaN,FK10 1BA,ALO,56.117863,-3.788579,Alloa
2,DG12 6AX,ANN,9451,NaN,NaN,NaN,DG12 6AX,ANN,54.983791,-3.263267,Annan
3,G13 1HX,ANL,9972,NaN,NaN,NaN,G13 1HX,ANL,55.890273,-4.322012,Anniesland
4,G21 4NA,BNL,9973,NaN,NaN,NaN,G21 4NA,BNL,55.878764,-4.223062,Barnhill
5,DD7 7RZ,BYL,9020,NaN,NaN,NaN,DD7 7RZ,BYL,56.4926,-2.746893,Barry Links
6,DD5 2AE,BYF,9023,NaN,NaN,NaN,DD5 2AE,BYF,56.467377,-2.874066,Broughty Ferry
7,ML5 1QQ,CBC,9747,NaN,NaN,NaN,ML5 1QQ,CBC,55.861997,-4.033197,Coatbridge Central
8,G52 1RB,CKH,9627,NaN,NaN,NaN,G52 1RB,CKH,55.836628,-4.334735,Corkerhill
9,KY15 5JD,CUP,9121,NaN,NaN,NaN,KY15 5JD,CUP,56.316514,-3.008178,Cupar
10,G40 4LR,DAK,9790,NaN,NaN,NaN,G40 4LR,DAK,55.842731,-4.218193,Dalmarnock
11,EH1 1BG,EDB,9328,NaN,NaN,NaN,EH1 1BG,EDB,55.951961,-3.189944,Edinburgh Waverley
12,EH1 1BG,EDB,9328,NaN,NaN,NaN,EH1 1BG,EDB,55.951961,-3.189944,Edinburgh Waverley
13,EH1 1BG,EDB,9328,NaN,NaN,NaN,EH1 1BG,EDB,55.951961,-3.189944,Edinburgh Waverley
14,EH1 1BG,EDB,9328,NaN,NaN,NaN,EH1 1BG,EDB,55.951961,-3.189944,Edinburgh Waverley
15,EH1 1BG,EDB,9328,NaN,NaN,NaN,EH1 1BG,EDB,55.951961,-3.189944,Edinburgh Waverley
16,EH1 1BG,EDB,9328,NaN,NaN,NaN,EH1 1BG,EDB,55.951961,-3.189944,Edinburgh Waverley
17,EH1 1BG,EDB,9328,NaN,NaN,NaN,EH1 1BG,EDB,55.951961,-3.189944,Edinburgh Waverley
18,EH1 1BG,EDB,9328,NaN,NaN,NaN,EH1 1BG,EDB,55.951961,-3.189944,Edinburgh Waverley
19,G69 8DF,GRH,9723,NaN,NaN,NaN,G69 8DF,GRH,55.88568,-4.079303,Gartcosh
20,G1 3SA,GLC,9813,NaN,NaN,NaN,G1 3SA,GLC,55.859295,-4.258192,Glasgow Central High Level
21,KY1 4ED,GLT,9301,NaN,NaN,NaN,KY1 4ED,GLT,56.161555,-3.143056,Glenrothes With Thornton
22,PA2 7AS,HKH,9634,NaN,NaN,NaN,PA2 7AS,HKH,55.841728,-4.399461,Hawkhead
23,AB54 6HZ,HNT,8921,NaN,NaN,NaN,AB54 6HZ,HNT,57.444558,-2.775875,Huntly
24,PA16 0AJ,IBM,9618,NaN,NaN,NaN,PA16 0AJ,IBM,55.942822,-4.741724,IBM
25,PH21 1JA,KIN,8655,NaN,NaN,NaN,PH21 1JA,KIN,57.077946,-4.053571,Kingussie
26,ML11 7NR,LNK,9710,NaN,NaN,NaN,ML11 7NR,LNK,55.673306,-3.772927,Lanark
27,G66 4LP,LNZ,9955,NaN,NaN,NaN,G66 4LP,LNZ,55.921262,-4.153919,Lenzie
28,PH33 7NW,LHE,8846,NaN,NaN,NaN,PH33 7NW,LHE,56.856166,-5.18696,Loch Eil Outward Bound
29,PA14 5JN,PTG,9667,NaN,NaN,NaN,PA14 5JN,PTG,55.933117,-4.690262,Port Glasgow
30,ML7 4BH,SHS,9739,NaN,NaN,NaN,ML7 4BH,SHS,55.819351,-3.799916,Shotts
31,G20 0HY,SUM,9959,NaN,NaN,NaN,G20 0HY,SUM,55.898513,-4.291439,Summerston
32,G81 1JQ,YOK,9990,NaN,NaN,NaN,G81 1JQ,YOK,55.892537,-4.38798,Yoker